// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIR850SOaxHpBHhFCF5ZJh3YT60E9atk',
    appId: '1:525631071445:web:e93b2ca046ac151726ae5c',
    messagingSenderId: '525631071445',
    projectId: 'social-app-ca1b2',
    authDomain: 'social-app-ca1b2.firebaseapp.com',
    storageBucket: 'social-app-ca1b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRAE3V33YYaP_9g5IlUzvLUCsBITJbPb0',
    appId: '1:525631071445:android:5251f81422ab24db26ae5c',
    messagingSenderId: '525631071445',
    projectId: 'social-app-ca1b2',
    storageBucket: 'social-app-ca1b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9jJeaU9fGqidRtWtwG57-nN_2MGNvss',
    appId: '1:525631071445:ios:893baf9110862a4126ae5c',
    messagingSenderId: '525631071445',
    projectId: 'social-app-ca1b2',
    storageBucket: 'social-app-ca1b2.firebasestorage.app',
    iosBundleId: 'com.example.hiveFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM9jJeaU9fGqidRtWtwG57-nN_2MGNvss',
    appId: '1:525631071445:ios:893baf9110862a4126ae5c',
    messagingSenderId: '525631071445',
    projectId: 'social-app-ca1b2',
    storageBucket: 'social-app-ca1b2.firebasestorage.app',
    iosBundleId: 'com.example.hiveFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaIR850SOaxHpBHhFCF5ZJh3YT60E9atk',
    appId: '1:525631071445:web:3d1b9dadb76b65a726ae5c',
    messagingSenderId: '525631071445',
    projectId: 'social-app-ca1b2',
    authDomain: 'social-app-ca1b2.firebaseapp.com',
    storageBucket: 'social-app-ca1b2.firebasestorage.app',
  );

}