// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:hive_firebase/features/authentication/domain/models/user_model.dart';
import 'package:hive_firebase/features/notes/domain/models/notes_model.dart';
import 'package:hive_firebase/features/sync_settings/sync_settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NotesModelAdapter());
    registerAdapter(SyncSettingsAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NotesModelAdapter());
    registerAdapter(SyncSettingsAdapter());
    registerAdapter(UserModelAdapter());
  }
}
